# Change these first
owner: NyaruDB # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Nyaru (Main)
    url: https://nyaru.xyz
  - name: Nyaru (Docs)
    url: https://docs.nyaru.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nyaru.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.nyaru.xyz/Nyaru/Nyaru_Square.png
  name: Nyaru Monitoring™
  introTitle: "Live Status Monitoring of Nyaru Services."
  introMessage: You can always visit our [community support server](https://go.nyaru.xyz/discord) for ANY kind of help.
  navbar:
    - title: Website
      href: https://nyaru.xyz/
    - title: Discord
      href: https://go.nyaru.xyz/discord

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
