owner: NyaruDB
repo: status

sites:
  - name: Nyaru (Main)
    url: https://nyaru.xyz
  - name: Nyaru (Docs)
    url: https://docs.nyaru.xyz

assignees:
  - NamVr
  - Sarveshmrao
  - Mr-Leonerrr
  - KrishGarg

status-website:
  cname: status.nyaru.xyz
  theme: dark
  favicon: https://cdn.nyaru.xyz/Nyaru/Nyaru_Square.png
  logoUrl: https://cdn.nyaru.xyz/Nyaru/Nyaru_Square.png
  name: Nyaru Monitoring™
  introTitle: "Live Status Monitoring of Nyaru Services."
  introMessage: You can always visit our [community support server](https://go.nyaru.xyz/discord) for ANY kind of help.
  navbar:
    - title: Website
      href: https://nyaru.xyz/
    - title: Discord
      href: https://go.nyaru.xyz/discord
